version: "3"
services:

 recipeservice:
  image: whatshouldieat/recipeservice
  depends_on:
  - mongodb
  networks:
  - backendnetwork
  environment:
    MONGO_DB_URI: mongodb://mongodb:27017/docker-db
  ports: 
  - 8080:8080

 mongodb:
  image: mongo
  networks:
  - backendnetwork
  ports:
  - 27017:27017

networks:
  backendnetwork:
    driver: bridge

 #frontend:
 # image: whatshouldieat-frontend
 # ports:
 # - 8082:8082

